Resources:
  miningPlants:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mining-plants-table
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: nombre
          AttributeType: S
        - AttributeName: empresa
          AttributeType: S
        - AttributeName: tipo_yacimiento
          AttributeType: S
        - AttributeName: estado_vigente
          AttributeType: S  
        - AttributeName: mineral_principal
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1      
      GlobalSecondaryIndexes:
        - IndexName: nombre
          KeySchema:
            - AttributeName: nombre
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1                   
        - IndexName: empresa
          KeySchema:
            - AttributeName: empresa
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: tipo_yacimiento
          KeySchema:
            - AttributeName: tipo_yacimiento
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: estado_vigente
          KeySchema:
            - AttributeName: estado_vigente
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: mineral_principal
          KeySchema:
            - AttributeName: mineral_principal
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1            


